// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLt1Y0JzrklOwLzKOk6b0qF6MeIg-_L3g',
    appId: '1:841098503341:web:8e966be5766f833b6d9224',
    messagingSenderId: '841098503341',
    projectId: 'foodfinderproject-ca2a6',
    authDomain: 'foodfinderproject-ca2a6.firebaseapp.com',
    storageBucket: 'foodfinderproject-ca2a6.firebasestorage.app',
    measurementId: 'G-VS2NN2KWF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjX5peRaEzS3GniiEpzV1H3P54kqoVjYc',
    appId: '1:841098503341:android:b5a04a45f1c993836d9224',
    messagingSenderId: '841098503341',
    projectId: 'foodfinderproject-ca2a6',
    storageBucket: 'foodfinderproject-ca2a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAryLrLnJVMHJStOQ3_UeP6f3OXHXuKQAY',
    appId: '1:841098503341:ios:29f265076d0c175c6d9224',
    messagingSenderId: '841098503341',
    projectId: 'foodfinderproject-ca2a6',
    storageBucket: 'foodfinderproject-ca2a6.firebasestorage.app',
    iosBundleId: 'com.example.foodfinderproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAryLrLnJVMHJStOQ3_UeP6f3OXHXuKQAY',
    appId: '1:841098503341:ios:29f265076d0c175c6d9224',
    messagingSenderId: '841098503341',
    projectId: 'foodfinderproject-ca2a6',
    storageBucket: 'foodfinderproject-ca2a6.firebasestorage.app',
    iosBundleId: 'com.example.foodfinderproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLt1Y0JzrklOwLzKOk6b0qF6MeIg-_L3g',
    appId: '1:841098503341:web:c99a05ca1f12a24a6d9224',
    messagingSenderId: '841098503341',
    projectId: 'foodfinderproject-ca2a6',
    authDomain: 'foodfinderproject-ca2a6.firebaseapp.com',
    storageBucket: 'foodfinderproject-ca2a6.firebasestorage.app',
    measurementId: 'G-94BN2P2FND',
  );

}